spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/movie
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      data-locations: classpath*:db/data.sql
      mode: always
      platform: h2

logging.level:
  org.hibernate:
    SQL: debug
    type.descriptor.sql: trace
